version: '3.8'
services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: job-hunter-db
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

    job-hunter:
        build: .
        ports:
            - '8002:3000'
        stdin_open: true
        tty: true
        depends_on:
            - db

volumes:
    mysql_data:
