import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import { NextAuthProvider } from './provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NextAuthProvider>
                    <Navbar />
                    <div className="pt-16">{children}</div>
                </NextAuthProvider>
            </body>
        </html>
    );
}
